name: Buildtools
description: Runs your build with buildtools
author: https://buildtools.io
requirements:
  - docker

configuration:
  properties:
    version:
      type: string
    config:
      type: string
  additionalProperties: false
